-- Water Usage Monitor - initial schema (Phase 1).
-- Managed by Flyway; Hibernate is set to `validate` only.

CREATE TABLE usage_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL,
    category         VARCHAR(32)      NOT NULL,
    litres           DOUBLE PRECISION NOT NULL,
    duration_minutes INTEGER,
    logged_at        TIMESTAMP        NOT NULL,
    notes            VARCHAR(500),
    adjusted_litres  DOUBLE PRECISION,
    created_at       TIMESTAMP        NOT NULL
);

CREATE INDEX idx_usage_user_logged
    ON usage_entries (user_id, logged_at);
CREATE INDEX idx_usage_user_category_logged
    ON usage_entries (user_id, category, logged_at);

CREATE TABLE goals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT           NOT NULL,
    category      VARCHAR(32),
    target_litres DOUBLE PRECISION NOT NULL,
    period        VARCHAR(16)      NOT NULL,
    state         VARCHAR(16)      NOT NULL,
    starts_at     DATE             NOT NULL,
    ends_at       DATE             NOT NULL,
    created_at    TIMESTAMP        NOT NULL
);

CREATE INDEX idx_goals_user ON goals (user_id);
CREATE INDEX idx_goals_state ON goals (state);

CREATE TABLE alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    type            VARCHAR(32)  NOT NULL,
    category        VARCHAR(32),
    message         VARCHAR(500) NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    acknowledged_at TIMESTAMP
);

CREATE INDEX idx_alerts_user_unacked
    ON alerts (user_id) WHERE acknowledged_at IS NULL;

CREATE TABLE regional_benchmarks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code        VARCHAR(16)      NOT NULL,
    category           VARCHAR(32)      NOT NULL,
    avg_litres_per_day DOUBLE PRECISION NOT NULL,
    season             VARCHAR(16)      NOT NULL,
    CONSTRAINT uq_benchmark UNIQUE (region_code, category, season)
);
